version: '3.9'
services:
  lb:
    image: dockercloud/haproxy
    links:
      - api-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  api-gateway:
    container_name: api-gateway
    image: microservices-workshop:dev
    restart: on-failure
    environment:
      - VIRTUAL_HOST=api-gateway.app.com
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway:/app/src

  delivery-service:
    container_name: delivery-service
    image: microservices-workshop:dev
    restart: on-failure
    volumes:
      - ./delivery-service:/app/src

  order-service:
    container_name: order-service
    image: microservices-workshop:dev
    restart: on-failure
    volumes:
      - ./order-service:/app/src

  restaurants-service:
    container_name: restaurants-service
    image: microservices-workshop:dev
    restart: on-failure
    volumes:
      - ./restaurants-service:/app/src
